import Foundation

let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
defer { try? FileManager.default.removeItem(at: root) }
let store = BackgroundDownloadStore(root: root.appendingPathComponent("persistent"))
let url = URL(string: "https://example.org/app.ipa?token=fixture")!
let first = BackgroundDownloadRecord(token: UUID(), id: "source/version?not-a-path", url: url, source: url, displayName: "Приложение")
let second = BackgroundDownloadRecord(token: UUID(), id: "second", url: url, source: url, displayName: "Другое")
var newAttempt = first
newAttempt.attempt = UUID()
try store.save(first); try store.save(second)
try store.save(newAttempt)
assert(store.records().first { $0.id == first.id }?.attempt == newAttempt.attempt)
assert(store.records().first { $0.id == first.id }?.attempt != first.attempt)
assert(store.records().count == 2)
assert(!store.isReady(first))
let systemTemp = root.appendingPathComponent("system-temp.ipa")
try Data([1,2,3,4]).write(to: systemTemp)
try store.receive(systemTemp, for: first)
assert(!FileManager.default.fileExists(atPath: systemTemp.path))
let restarted = BackgroundDownloadStore(root: store.root)
assert(restarted.records().contains { $0.token == first.token && $0.id == first.id })
assert(restarted.isReady(first))
let received = try Data(contentsOf: restarted.packageURL(first))
assert(received == Data([1,2,3,4]))
// A broken metadata file cannot hide other downloads, and record IDs never become paths.
try Data("not JSON".utf8).write(to: store.root.appendingPathComponent("broken.json"))
assert(restarted.records().count == 2)
assert(restarted.packageURL(first).path.hasPrefix(store.root.path + "/"))
try restarted.remove(second)
assert(restarted.isReady(first) && restarted.records().count == 1)
try restarted.remove(first)
assert(!restarted.isReady(first) && restarted.records().isEmpty)
print("Background download persistence: receive, relaunch, corrupt metadata isolation and cancellation passed")

let documents = root.appendingPathComponent("Documents")
let temporary = root.appendingPathComponent("tmp")
let transfers = root.appendingPathComponent("Transfers")
func fixture(_ directory: URL, _ count: Int) throws {
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    try Data(repeating: 1, count: count).write(to: directory.appendingPathComponent("fixture.dat"))
}
try fixture(documents.appendingPathComponent("Signed/orphan"), 300)
try fixture(documents.appendingPathComponent("Unsigned/app"), 200)
try fixture(documents.appendingPathComponent("Archives"), 400)
try fixture(documents.appendingPathComponent("Certificates"), 100)
let work = temporary.appendingPathComponent("FeatherInstall_" + UUID().uuidString)
let system = temporary.appendingPathComponent("com.apple.nsurlsessiond")
try fixture(work, 600)
try fixture(system, 700)
try fixture(temporary.appendingPathComponent("FeatherImport_not-an-owned-UUID"), 800)
try fixture(transfers, 900)
let before = LocalAppFiles.snapshot(documents: documents, temporary: temporary, transfers: transfers)
assert(before.apps == 500 && before.archives == 400 && before.work == 600 && before.transfers == 900 && before.other == 100 && before.total == 2500)
try LocalAppFiles.clearWork(in: temporary)
try LocalAppFiles.clearChildren(in: documents.appendingPathComponent("Signed"))
try LocalAppFiles.clearChildren(in: documents.appendingPathComponent("Unsigned"))
assert(LocalAppFiles.size(of: system) == 700)
assert(LocalAppFiles.size(of: temporary.appendingPathComponent("FeatherImport_not-an-owned-UUID")) == 800)
assert(LocalAppFiles.size(of: transfers) == 900)
let after = LocalAppFiles.snapshot(documents: documents, temporary: temporary, transfers: transfers)
assert(after.apps == 0 && after.work == 0 && after.archives == 400 && after.other == 100 && after.total == 1400)
try Data([1]).write(to: system.appendingPathComponent("next-download.tmp"))
print("Storage regression: accurate breakdown, orphan cleanup, session-folder reuse, credentials/archives/transfers preservation passed")
